name: Node.js Package

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      couchdb:
        image: couchdb
        ports:
          - 5984:5984
      mongo:
        image: mongo
        ports:
          - 27017:27017
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ueberdb
          MYSQL_DATABASE: ueberdb
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      postgres:
        image: postgres
        ports:
          - 5432:5432
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: sudo /etc/init.d/mysql start
      # Verify databases are reachable.
      - name: Verify MySQL connection
        run: |
          mysql -h localhost -uroot -pueberdb -e "SHOW DATABASES"
      - run: npm test
      - run: npm run lint

  publish-npm:
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: git config user.name 'github-actions[bot]'
      - run: git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - run: npm ci
      - run: npm version patch
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: git push --follow-tags
